services:
  # The Laravel Application
  - type: web
    name: sga-app
    runtime: docker
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
